[package]
name = "rust_lib_cooking_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
chrono = "0.4.41"
flutter_rust_bridge = "=2.10.0"
serde = "1.0.219"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
